## Numpy

In [1]:
import numpy as np

1. Создайте вектор состоящий из чисел от 0 до 11 включительно. 

In [69]:
A = np.arange(0, 12)

2. Измените размерность вектора и превратите его в матрицу 3 х 4

In [95]:
A = a.reshape((3,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

3. Найдите произведение полученной матрицы и вектора [2, 3, 5, 6]

In [74]:
v = np.array([2,3,5,6])
mult = A.dot(v)
mult

array([ 31,  95, 159])

4. Из матрицы из пункта 2 сделайте квадратную матрицу состоящую из строк с индексами 0, 1, 3

In [96]:
A = A.T[[0, 1, 3]].T
A

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

5. Найдите обратную матрицу к полученной в пункте 4.

In [97]:
A_inv = np.linalg.inv(A)

LinAlgError: Singular matrix

6. Проверьте является ли она обратной?

In [98]:
A.dot(A_inv)

NameError: name 'A_inv' is not defined

## Pandas

1. Загрузите данные из https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv в DataFrame. Воспользуйтесь одним из способов предложенных на занятии.

In [54]:
import pandas as pd
url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
df = pd.read_csv(url)
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

2. Выведите несколько первых строк таблицы. 

In [55]:
df.head(5)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

3. Отфильруйте машины по марке и оставьте только строки с автомобилями BMW. 

In [56]:
df_BMW = df[df['Make'] == 'BMW']

4. Найдите среднюю стоимость автомобиля BMW и выведите данное значение с точность до двух знаком после запятой.

In [57]:
print('Средняя стоимость автомобиля BMW:', round(df_BMW.groupby('Make')['MSRP'].mean().iloc[0], 2))

Средняя стоимость автомобиля BMW: 61546.76


5. Определите каких автомобилей больше с ручной коробокой передач или автоматической?

In [58]:
print('Количество автомобилей BMW с автоматической коробкой передач:', df_BMW[df_BMW['Transmission Type'] == 'AUTOMATIC'].shape[0])
print('Количество автомобилей BMW с ручной коробкой передач:', df_BMW[df_BMW['Transmission Type'] == 'MANUAL'].shape[0])

Количество автомобилей BMW с автоматической коробкой передач: 255
Количество автомобилей BMW с ручной коробкой передач: 57


In [59]:
print('Количество всех автомобилей с автоматической коробкой передач:', df[df['Transmission Type'] == 'AUTOMATIC'].shape[0])
print('Количество всех автомобилей с ручной коробкой передач:', df[df['Transmission Type'] == 'MANUAL'].shape[0])

Количество всех автомобилей с автоматической коробкой передач: 8266
Количество всех автомобилей с ручной коробкой передач: 2935
